version: "3.8"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - MONGO_URI=mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongodb:27017/AfrikanWears
      - REDIS_URL=redis://redis:6379
      - REQUIRED_VARS=JWT_SECRET,GMAIL_PASSWORD,SANITY_WRITE_TOKEN
    depends_on:
      - mongodb
      - redis
    restart: unless-stopped
    networks:
      - app_network

  mongodb:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    restart: unless-stopped
    networks:
      - app_network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - app_network

volumes:
  mongodb_data:
  redis_data:

networks:
  app_network:
    driver: bridge
