name: Docker CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_BUILDKIT: 1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Install docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose-plugin -y
          # Check if installation was successful
          docker compose version || docker-compose version

      - name: Build and push
        run: |
          docker compose -f docker-compose.yml build 
          docker compose -f docker-compose.yml push
